---
- hosts: all
  sudo: yes
  tasks:
  - name: install apache2
    apt: name=apache2 update_cache=yes state=latest

# https://www.digitalocean.com/community/tutorials/how-to-configure-apache-using-ansible-on-ubuntu-14-04
